//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdelantosOrdenVenta
    {
        public int Id { get; set; }
        public int IdOrdenVenta { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuario { get; set; }
        public string Motivo { get; set; }
    
        public virtual OrdenVenta OrdenVenta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
