//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class AjusteInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AjusteInventario()
        {
            this.AjusteInventarioDetalle = new HashSet<AjusteInventarioDetalle>();
        }
    
        public int id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int idAlmacen { get; set; }
        public string Motivo { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime FechaAprobacion { get; set; }
        public Nullable<int> IdUsuarioAprobacion { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AjusteInventarioDetalle> AjusteInventarioDetalle { get; set; }
    }
}
