//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoCorriativoOrdenTrabajo
    {
        public int Id { get; set; }
        public int IdOrdenTrabajo { get; set; }
        public string HojasAut { get; set; }
        public string CantidadAut { get; set; }
        public Nullable<bool> CbAUt { get; set; }
        public string ValorCbAut { get; set; }
        public Nullable<bool> cbCfAut { get; set; }
        public string ValorCfAut { get; set; }
        public Nullable<bool> CfbAut { get; set; }
        public string ValorCfbAut { get; set; }
        public Nullable<bool> CfbAut1 { get; set; }
        public string ValorCfbAut1 { get; set; }
        public Nullable<bool> CfbAut2 { get; set; }
        public string ValorCfbAut2 { get; set; }
    
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
