//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaTrabajo
    {
        public int IdCategoriaTrabajo { get; set; }
        public Nullable<int> IdOrdenTrabajo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string DescripcionGeneral { get; set; }
        public string DescripcionEspecifica { get; set; }
    
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
