//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComprobanteVenta()
        {
            this.ComprobanteVentaDetalle = new HashSet<ComprobanteVentaDetalle>();
        }
    
        public int IdComprobanteVenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Serie { get; set; }
        public int Numero { get; set; }
        public int IdPersona { get; set; }
        public double IGV { get; set; }
        public double Total { get; set; }
        public Nullable<double> Descuento { get; set; }
        public int IdTipoDocumento { get; set; }
        public Nullable<int> IdMotivoComprobante { get; set; }
        public Nullable<int> IdComprobanteVentaRef { get; set; }
        public int IdCaja { get; set; }
        public string Observacion { get; set; }
        public int IdEstado { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> IdentificadorProcedencia { get; set; }
        public Nullable<int> IdOrdenVenta { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdTipoPago { get; set; }
        public string Tarjeta { get; set; }
        public string Digitos { get; set; }
        public string MotivoNotaCredito { get; set; }
    
        public virtual MotivoComprobante MotivoComprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteVentaDetalle> ComprobanteVentaDetalle { get; set; }
    }
}
