//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteVentaDetalle
    {
        public int Id { get; set; }
        public int IdComprobanteVenta { get; set; }
        public Nullable<int> IdOrdenVentaDetalle { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string TipoMoneda { get; set; }
        public Nullable<decimal> Equivalencia { get; set; }
        public Nullable<decimal> PrecioDolar { get; set; }
    
        public virtual ComprobanteVenta ComprobanteVenta { get; set; }
        public virtual OrdenVentaDetalle OrdenVentaDetalle { get; set; }
    }
}
