//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteVentaAuxiliar
    {
        public int IdComprobanteVentaAuxiliar { get; set; }
        public string Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Serie { get; set; }
        public string Numero { get; set; }
        public string RazonSocial { get; set; }
        public string Total { get; set; }
        public string Motivo { get; set; }
        public string Caja { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public string Usuario { get; set; }
        public string IdOrdenVenta { get; set; }
        public string TipoPago { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string NotasCredito { get; set; }
    }
}
