//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int IdConfiguracion { get; set; }
        public double DolarCompra { get; set; }
        public double DolarVenta { get; set; }
        public double IGV { get; set; }
        public string RUC { get; set; }
        public string RazonSocial { get; set; }
        public string Direccion01 { get; set; }
        public string Direccion02 { get; set; }
        public string Telefonos { get; set; }
        public string Celulares { get; set; }
    }
}
