//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FayceEntities : DbContext
    {
        public FayceEntities()
            : base("name=FayceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccesoTipo> AccesoTipo { get; set; }
        public virtual DbSet<AjusteInventario> AjusteInventario { get; set; }
        public virtual DbSet<AjusteInventarioDetalle> AjusteInventarioDetalle { get; set; }
        public virtual DbSet<Almacen> Almacen { get; set; }
        public virtual DbSet<AutoCorriativoOrdenTrabajo> AutoCorriativoOrdenTrabajo { get; set; }
        public virtual DbSet<BodegaInventarioOrdenTrabajo> BodegaInventarioOrdenTrabajo { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<CategoriaTrabajo> CategoriaTrabajo { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<ComprobanteVenta> ComprobanteVenta { get; set; }
        public virtual DbSet<ComprobanteVentaAuxiliar> ComprobanteVentaAuxiliar { get; set; }
        public virtual DbSet<ComprobanteVentaDetalle> ComprobanteVentaDetalle { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
        public virtual DbSet<CorrelativoComprobante> CorrelativoComprobante { get; set; }
        public virtual DbSet<Cotizacion> Cotizacion { get; set; }
        public virtual DbSet<CotizacionDetalle> CotizacionDetalle { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Egresos> Egresos { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Formulario> Formulario { get; set; }
        public virtual DbSet<MarcaMaterial> MarcaMaterial { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<MenuPerfil> MenuPerfil { get; set; }
        public virtual DbSet<MotivoComprobante> MotivoComprobante { get; set; }
        public virtual DbSet<OperadorOrdenTrabajo> OperadorOrdenTrabajo { get; set; }
        public virtual DbSet<OrdenCompra> OrdenCompra { get; set; }
        public virtual DbSet<OrdenCompraDetalle> OrdenCompraDetalle { get; set; }
        public virtual DbSet<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual DbSet<OrdenVenta> OrdenVenta { get; set; }
        public virtual DbSet<OrdenVentaDetalle> OrdenVentaDetalle { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<PosPrensaOrdenTrabajo> PosPrensaOrdenTrabajo { get; set; }
        public virtual DbSet<PrensaOrdenTrabajo> PrensaOrdenTrabajo { get; set; }
        public virtual DbSet<PresentacionMaterial> PresentacionMaterial { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Recepcion> Recepcion { get; set; }
        public virtual DbSet<RecepcionDetalle> RecepcionDetalle { get; set; }
        public virtual DbSet<Reporte> Reporte { get; set; }
        public virtual DbSet<Requerimiento> Requerimiento { get; set; }
        public virtual DbSet<RequerimientoDetalle> RequerimientoDetalle { get; set; }
        public virtual DbSet<SalidaMaterial> SalidaMaterial { get; set; }
        public virtual DbSet<SalidaMaterialesDetalle> SalidaMaterialesDetalle { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockTransaccion> StockTransaccion { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoEstado> TipoEstado { get; set; }
        public virtual DbSet<TipoPago> TipoPago { get; set; }
        public virtual DbSet<TipoProfesion> TipoProfesion { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<TransferenciaStock> TransferenciaStock { get; set; }
        public virtual DbSet<TransferenciaStockDetalle> TransferenciaStockDetalle { get; set; }
        public virtual DbSet<UnidadMedida> UnidadMedida { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<AdelantosOrdenVenta> AdelantosOrdenVenta { get; set; }
    }
}
