//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuPerfil
    {
        public int IdMenuPerfil { get; set; }
        public int IdMenuPadre { get; set; }
        public int IdMenuHijo { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<bool> SoloLectura { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
