//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenTrabajo()
        {
            this.AutoCorriativoOrdenTrabajo = new HashSet<AutoCorriativoOrdenTrabajo>();
            this.BodegaInventarioOrdenTrabajo = new HashSet<BodegaInventarioOrdenTrabajo>();
            this.CategoriaTrabajo = new HashSet<CategoriaTrabajo>();
            this.OperadorOrdenTrabajo = new HashSet<OperadorOrdenTrabajo>();
            this.PosPrensaOrdenTrabajo = new HashSet<PosPrensaOrdenTrabajo>();
            this.PrensaOrdenTrabajo = new HashSet<PrensaOrdenTrabajo>();
            this.SalidaMaterial = new HashSet<SalidaMaterial>();
        }
    
        public int IdOrdenTrabajo { get; set; }
        public string Trabajo { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaEntregaO { get; set; }
        public System.DateTime FechaEntregaF { get; set; }
        public int IdEjecutivo { get; set; }
        public Nullable<int> IdClienteNatural { get; set; }
        public Nullable<int> IdClienteJuridico { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> NumeroSelecciones { get; set; }
        public Nullable<int> NumeroPlacasUnColor { get; set; }
        public Nullable<int> TotalPlacas { get; set; }
        public Nullable<int> NumeroOrdenado { get; set; }
        public string Maquina { get; set; }
        public Nullable<int> PagPortada { get; set; }
        public Nullable<int> PaginaInteriores { get; set; }
        public string TamañoAbierto { get; set; }
        public string Colores { get; set; }
        public string Liniaje { get; set; }
        public Nullable<bool> Paneles { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Ctp { get; set; }
        public Nullable<bool> Canson { get; set; }
        public int IdEstado { get; set; }
        public string Operadores { get; set; }
        public string OperadoresBodegaInventario { get; set; }
        public string ComentariosBodegaInventario { get; set; }
        public string OperadoresPrensa { get; set; }
        public string ComentariosPrensa { get; set; }
        public string OperadoresPosPrensa { get; set; }
        public string ComentariosPosPrensa { get; set; }
        public Nullable<int> IdOrdenVentaDetalle { get; set; }
        public Nullable<int> CantidadPliegos { get; set; }
        public string DescripcionPliegos { get; set; }
        public string DemasiaPliegos { get; set; }
        public string MedidaPliegos { get; set; }
        public string TamañoCortePliego { get; set; }
        public Nullable<int> CantidadResmas { get; set; }
        public string DescripcionResmas { get; set; }
        public string DemasiaResmas { get; set; }
        public string MedidaResmas { get; set; }
        public string TamañoCorteResmas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoCorriativoOrdenTrabajo> AutoCorriativoOrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BodegaInventarioOrdenTrabajo> BodegaInventarioOrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriaTrabajo> CategoriaTrabajo { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperadorOrdenTrabajo> OperadorOrdenTrabajo { get; set; }
        public virtual OrdenVentaDetalle OrdenVentaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosPrensaOrdenTrabajo> PosPrensaOrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrensaOrdenTrabajo> PrensaOrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalidaMaterial> SalidaMaterial { get; set; }
    }
}
