//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenVentaDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenVentaDetalle()
        {
            this.ComprobanteVentaDetalle = new HashSet<ComprobanteVentaDetalle>();
            this.OrdenTrabajo = new HashSet<OrdenTrabajo>();
        }
    
        public int Id { get; set; }
        public int IdOrdenVenta { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> IdCotizacionDetalle { get; set; }
        public string TipoMoneda { get; set; }
        public Nullable<decimal> Equivalencia { get; set; }
        public Nullable<decimal> PrecioDolar { get; set; }
        public int IdUnidadMedida { get; set; }
        public string Observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteVentaDetalle> ComprobanteVentaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual OrdenVenta OrdenVenta { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
    }
}
