//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosPrensaOrdenTrabajo
    {
        public int IdPosPrensaOrdenTrabajo { get; set; }
        public int IdOrdenTrabajo { get; set; }
        public Nullable<bool> Numerado { get; set; }
        public Nullable<bool> Compaginado { get; set; }
        public Nullable<bool> Perforado { get; set; }
        public Nullable<bool> Anillado { get; set; }
        public Nullable<int> Del { get; set; }
        public Nullable<int> Al { get; set; }
        public Nullable<bool> Encolado { get; set; }
        public Nullable<bool> Troquelado { get; set; }
        public Nullable<bool> DobleRing { get; set; }
        public Nullable<bool> Engrampado { get; set; }
        public Nullable<bool> Refilado { get; set; }
        public Nullable<bool> Barnizado { get; set; }
        public Nullable<bool> Plastificado { get; set; }
        public Nullable<bool> Mate { get; set; }
        public Nullable<bool> Brillante { get; set; }
        public Nullable<bool> Tira { get; set; }
        public Nullable<bool> TiraRetira { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<bool> Mate1 { get; set; }
        public Nullable<bool> Brillante1 { get; set; }
        public Nullable<bool> Tira1 { get; set; }
        public Nullable<bool> RetiraRetira1 { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
