//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrensaOrdenTrabajo
    {
        public int IdPrensaOrdenTrabajo { get; set; }
        public int IdOrdenTrabajo { get; set; }
        public string Trabajo { get; set; }
        public string Tamaño { get; set; }
        public string Tiros { get; set; }
        public string Demasia { get; set; }
        public string Tira { get; set; }
        public string Retira { get; set; }
        public string P_Exceso { get; set; }
        public string T { get; set; }
        public string T_R { get; set; }
        public string T_Plus_R { get; set; }
        public string Maquina { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
