//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecepcionDetalle
    {
        public int Id { get; set; }
        public int IdRecepcion { get; set; }
        public int IdMaterial { get; set; }
        public int Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> ValorUnitarioSinFlete { get; set; }
        public Nullable<int> CantidadRecibida { get; set; }
        public Nullable<bool> RecepcionTotal { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> IdOrdenCompraDetalle { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Recepcion Recepcion { get; set; }
    }
}
