//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recepcion()
        {
            this.RecepcionDetalle = new HashSet<RecepcionDetalle>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdEmpresa { get; set; }
        public int IdTipoDocumento { get; set; }
        public Nullable<int> IdOrdenCompra { get; set; }
        public string SerieComprobante { get; set; }
        public Nullable<int> NumeroComprobante { get; set; }
        public string SerieGuiaRemision { get; set; }
        public Nullable<int> NumeroGuiaRemision { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int IdAlmacen { get; set; }
        public int IdEstado { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioUltimaModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<double> ValorFlete { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual OrdenCompra OrdenCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecepcionDetalle> RecepcionDetalle { get; set; }
    }
}
