//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalidaMaterial()
        {
            this.SalidaMaterialesDetalle = new HashSet<SalidaMaterialesDetalle>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdClienteNatural { get; set; }
        public Nullable<int> IdClienteJuridico { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string DocumentoReferencia { get; set; }
        public string TipoSalidaMaterial { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<decimal> AdelantoPago { get; set; }
        public Nullable<int> IdOrdenTrabajo { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalidaMaterialesDetalle> SalidaMaterialesDetalle { get; set; }
    }
}
