//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferenciaStockDetalle
    {
        public int Id { get; set; }
        public int IdTransferenciaStock { get; set; }
        public int IdMaterial { get; set; }
        public double Cantidad { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual TransferenciaStock TransferenciaStock { get; set; }
    }
}
