//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDatos.Fay_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadMedida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnidadMedida()
        {
            this.CotizacionDetalle = new HashSet<CotizacionDetalle>();
            this.OrdenVentaDetalle = new HashSet<OrdenVentaDetalle>();
            this.RequerimientoDetalle = new HashSet<RequerimientoDetalle>();
            this.SalidaMaterialesDetalle = new HashSet<SalidaMaterialesDetalle>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionDetalle> CotizacionDetalle { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenVentaDetalle> OrdenVentaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequerimientoDetalle> RequerimientoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalidaMaterialesDetalle> SalidaMaterialesDetalle { get; set; }
    }
}
